default:
  tags:
    - service

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - check
  - build
  - deploy

check-job:
  stage: check
  script:
    - docker info

build-job:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - >
      docker build
      -t $CI_REGISTRY_IMAGE
      --build-arg KAKAO_REST_API_KEY="$KAKAO_REST_API_KEY"
      --build-arg MONGODB_URI="$MONGODB_URI"
      --build-arg KAKAO_REDIRECT_URI="$KAKAO_REDIRECT_URI"
      --no-cache .
    - docker push $CI_REGISTRY_IMAGE

deploy-job:
  stage: deploy
  script:
    - docker rm -f $CI_PROJECT_PATH_SLUG
    - >
      docker run -d
      --name $CI_PROJECT_PATH_SLUG
      --restart always
      -e KAKAO_REST_API_KEY="$KAKAO_REST_API_KEY"
      -e MONGODB_URI="$MONGODB_URI"
      -e KAKAO_REDIRECT_URI="$KAKAO_REDIRECT_URI"
      --label traefik.enable=true
      --label traefik.http.routers.$CI_PROJECT_PATH_SLUG.entrypoints=https,http
      --label traefik.http.routers.$CI_PROJECT_PATH_SLUG.rule='Host(`dimigo.net`)'
      --label traefik.http.routers.$CI_PROJECT_PATH_SLUG.tls=true
      --label traefik.http.routers.$CI_PROJECT_PATH_SLUG.tls.certresolver=letsencrypt
      --label traefik.http.routers.$CI_PROJECT_PATH_SLUG.service=$CI_PROJECT_PATH_SLUG
      --label traefik.http.routers.$CI_PROJECT_PATH_SLUG.middlewares=error-handler@file
      --label traefik.http.services.$CI_PROJECT_PATH_SLUG.loadbalancer.server.port=3000
      --network proxy
      $CI_REGISTRY_IMAGE:latest
